### ISSUE TITLE
Small Angle Odometry Inaccuracies

### ISSUE THREAD

**Issue by albertcai101** [KuriosityRobotics/SkyStone#10]
Going forward and backward: perfect
Going forward, turning, turning back, backward: perfect
Going forward, turning, going forward, going backward, turning back, going backward: 0.1"-0.3" on each axis
Going forward, random movements including mecanum, going backward: 0.5"-0.5" on each axis

400% more accurate than last year (hopefully thanks to faster update speeds), and we are still doing small-angle odometry.

It is still not accurate enough though.

We will get more data and graphs

**Comment by albertcai101** [comment]
By using update speeds from 66 Hz to 100 Hz:

Going forward, and arc turning and stuff (no mecanum): 0.05"-0.12" on each axis

Still though, similar measurements, random movements including mecanum still 0.5" average error on each axis

**Comment by albertcai101** [comment]
Odometry errors are WAYYY better when we move slower: ~0.3 power

**Comment by e3l** [comment]
@albertcai101 Is this still relevant? Or will we pursue circular odometry.

**Comment by albertcai101** [comment]
Still relevant, not accurate enough still but a lot better than before

**Comment by e3l** [comment]
We'll be working to perfect circularOdometry rather than smallAngle now.
