### ISSUE TITLE
Sometimes encoder values are non-zero when OpMode starts

### ISSUE THREAD

**Issue by albertcai101** [KuriosityRobotics/SkyStone#14]
even when we do a long init, there's some bug

**Comment by e3l** [comment]
Could be because the encoders are not given enough time to reset -- see [EncodersFix branch](https://github.com/KuriosityRobotics/SkyStone/tree/EncodersFix) for a possible solution. @albertcai101 can you test this?

**Comment by albertcai101** [comment]
fixed itself
