### ISSUE TITLE
Waypoint Management

### ISSUE THREAD

**Issue by chop0** [KuriosityRobotics/SkyStone#17]
Waypoints could be managed in some sort of queue, where the drivetrain constantly will go to the next waypoint in the queue. The waypoint could have a function to be executed when the robot arrives, which when complete, the waypoint would be removed off the queue and the drivetrain would move to the next one. Alternatively, each waypoint could just have a boolean saying if they've been completed or not, and the drivetrain just checks that before moving onto the next one

**Comment by e3l** [comment]
I will work on this as I apply Pure Pursuit, which is how the robot will move through autonomous.
